# Generated by Django 5.0.1 on 2024-01-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('text_msg', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('finish_time', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCodeMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
                ('phone_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.phonecode')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='filter_phone_code',
            field=models.ManyToManyField(through='mailing.PhoneCodeMailing', to='mailing.phonecode', verbose_name='Фильтр клиентов по коду мобильного оператора'),
        ),
        migrations.CreateModel(
            name='TagMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.tag')),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='filter_tag',
            field=models.ManyToManyField(through='mailing.TagMailing', to='mailing.tag', verbose_name='Фильтр клиентов по тегу'),
        ),
        migrations.AddConstraint(
            model_name='phonecodemailing',
            constraint=models.UniqueConstraint(fields=('phone_code', 'mailing'), name='unique_phone_code_mailing'),
        ),
        migrations.AddConstraint(
            model_name='tagmailing',
            constraint=models.UniqueConstraint(fields=('tag', 'mailing'), name='unique_tag_mailing'),
        ),
    ]
