version: "3.9"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
