version: '3.9'
services:
  db:
    image: postgres:16.1-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    expose:
      - '${DB_PORT}'
    networks:
      - backend
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - backend
      - frontend
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - '8000:80'
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
  frontend: