version: '3.8'
services:
  db:
    container_name: db
    image: postgres:16.1-bullseye
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - '5432:5432'

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 config.asgi -w 4 -k uvicorn.workers.UvicornWorker --timeout 60
    #    command: python -m uvicorn --host 0.0.0.0 --port 8000 config.asgi:application --lifespan off --reload
    #    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    restart: always
    command: redis-server
    ports:
      - '6379:6379'

  celery:
    container_name: celery
    restart: always
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    command: celery -A config worker -l info -E
    env_file:
      - .env
    depends_on:
      - app
      - redis

volumes:
  postgres_data:
